### ISSUE TITLE
Custom keybindings on OS X

### ISSUE THREAD

**Issue by bkamins** [bkamins/SilverDecisions#61]
@mwasiluk Is it possible and simple to detect if SilverDecisions runs on OS X.
On OS X we should have the following remapings:

Ctrl-C/V/X => Cmd-C/V/X

This is not crucial to have (but if it is simple it would be nice to have) - that's why this is a question (we can simply highlight in documentation that Ctrl should be also used on OS X, but users report that it is not intuitive there)

**Comment by mwasiluk** [comment]
I could add additional key event handlers (event.metaKey) like described in 
http://stackoverflow.com/questions/3902635/how-does-one-capture-a-macs-command-key-via-javascript

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/metaKey

But I don't have mac, so i can't test it myself.

**Comment by bkamins** [comment]
@michaljakubczyk Please test this and #18 reasonably fast as we want to go with 0.4 to production. I have published current dev on http://bogumilkaminski.pl/sddev/.
If everything is OK please close this issue and update the documentation as needed.
If you feel we need to update the About dialog then write a recommendation what should be changed.

**Comment by bkamins** [comment]
@michaljakubczyk I assume this is done and OK. If anything shows up we will correct it after release of 0.4. Just please remember to document it and then I will close the issue.

**Comment by michaljakubczyk** [comment]
Cmd+C/X/V/Z/Y still do not work (Ctrl+xxx works fine) on Mac+Safari. It might be difficult to handle, as in the application menu the commands copy/paste/... are greyed out, and cannot even be selected with a mouse-click. It will probably be difficult to handle this issue, not having a Mac during the development process :) I'd say, let's forget about it right now.

**Comment by bkamins** [comment]
So you say that you are not able to perform copy from context menu (using mouse)?

**Comment by bkamins** [comment]
Have you tested other browsers (Chrome, FireFox) under OS X.

**Comment by bkamins** [comment]
@mwasiluk please reverse the commit and we do not support `Cmd` and close the issue then.
